### ISSUE TITLE
TASK backend functionality for password reset

### ISSUE THREAD

**Issue by williamirva** [APUOPE-RE/backend#14]
Under this task, the functionality to handle password reset requests should be implemented in the backend.

- [x] Create a new POST endpoint that accepts a user’s email address.
- [x] Validate that email exists in the database.
- [x] Generate time-limited token and store it to database associated with the account.
- [x] Send an email to the user with a reset link containing the token
- [x] Create a new POST endpoint that accepts a new password and the reset token.
- [x] Validate the reset token to ensure it is valid and not expired.
- [x] Hash the new password and update it to database
- [x] Invalidate the reset token and send OK response to frontend

Subtask of APUOPE-RE/wiki#12

**Comment by roosavihlman** [comment]
As there is not yet implemented password hashing functionality, let's implement it under this ticket since one of the requirements is to hash the new password.
