### ISSUE TITLE
TASK implement saving of old conversations to database

### ISSUE THREAD

**Issue by williamirva** [APUOPE-RE/backend#21]
Under this issue, the functionality to store user conversations with the AI in the database should be implemented.

- [x] Implement database table to store old coversation data
Table could have atleast:
- coversation id
- user id
- timestamp
- Coversation data (text or JSON maybe?)

One possible solution is that every input and response is stored as a row to table and with conversation id we can identify which data belongs to which conversation. This way we can give content of single conversation by gathering all the rows with same id to frontend and frontend can show the conversation bubbles in correct order based on timestamps.

- [x] Create backend functionality to store conversation data to database.

Subtask of APUOPE-RE/wiki#
Specifications: https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Conversation-History

**Comment by williamirva** [comment]
How user can continue old conversation?

**Comment by roosavihlman** [comment]
PR backend: https://github.com/APUOPE-RE/backend/pull/33
PR frontend; https://github.com/APUOPE-RE/frontend/pull/47
