### ISSUE TITLE
TASK Log in -page, backend

### ISSUE THREAD

**Issue by mohes7489** [APUOPE-RE/backend#3]
Under this ticket, there is implemented backend functionality for the log in page. 

Implementation includes:
- working REST endpoints
- data transfer between frontend and database
- error handling
- necessary unit tests.

Sub task of ticket APUOPE-RE/Wiki#9
Specifications: https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Log-In-&-Sign-Up

**Comment by williamirva** [comment]
How the authentication will be done  between frontend and backend.

**Comment by roosavihlman** [comment]
> How the authentication will be done between frontend and backend.

I guess we could do a separate ticket to tackle this issue just to get the application's main functionality first up and running. Authentication is all in all easy to add everywhere it is needed beforehand.
