### ISSUE TITLE
TASK backend delete old conversation

### ISSUE THREAD

**Issue by williamirva** [APUOPE-RE/backend#31]
- [x] Create endpoint to delete old conversation

**Comment by roosavihlman** [comment]
PR: https://github.com/APUOPE-RE/backend/pull/36

- Created an endpoint to call conversation deletion method
    - Takes conversation id as a parameter
- Created a method that calls chat bot repository to remove conversation
- In chat bot repository created query which first deletes messages of a conversation and then conversation

Also edited the message table's content (the message text) in db to type TEXT so the length isn't restricted.

**Comment by roosavihlman** [comment]
The upper PR was reverted because there were two PRs with migration files so this one's needed to be renamed.

New PR: https://github.com/APUOPE-RE/backend/pull/38
