### ISSUE TITLE
TASK Create Quiz Generation Feature

### ISSUE THREAD

**Issue by williamirva** [APUOPE-RE/backend#39]
Develop a backend feature that allows users to generate a quiz from a selected textbook chapter. The backend should send the content of the chapter to an LLM and request it to create a quiz. The resulting quiz data will be sent to the frontend for rendering.

- [x] Create endpoint which returns data for creating quiz in frontend. Should take at least lectureId and userId.
- [x] Ask for LLM to create quiz questions and answers based on the context.
- [x] Quiz questions and correct answers should be saved to db.
- [x] In response there could be Json including questions and their options
- [x] Implement error handling if the quiz generation fails.

Idea of the response format:

{
  "quiz": {
    "lectureId": "<lectureId>",
    "questions": [
      {
        "question": "<question_text>",
        "options": ["<option_1>", "<option_2>", "<option_3>", "<option_4>"],
      },
      ...
    ]
  }
}

NOTE: Their separate issue where users answers are checked and correct answers are provided.

**Comment by roosavihlman** [comment]
PR Front: https://github.com/APUOPE-RE/frontend/pull/93
PR Back: https://github.com/APUOPE-RE/backend/pull/47
