### ISSUE TITLE
TASK Register page, backend

### ISSUE THREAD

**Issue by williamirva** [APUOPE-RE/backend#6]
Under this issue backend endpoint and logic for registering a new user to application is done.

Endpoint should receive username, password and email of the new user from the frontend POST-request. 

- [x] Validate the username, password and email.
- [x] Check that the email and username doesn't already exist in the system.
- [ ] Hash the password before storing to database
- [x] Store user information to db

subatsk of APUOPE-RE/Wiki#13 
Specifications: https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Log-in-&-Registration

**Comment by williamirva** [comment]
Email needs to be confirmed. This will bring some extra work. If email confirmation seems to be very large task, then lets separate it to its own issue.

**Comment by roosavihlman** [comment]
**Edit 1.10.2024:** Updated specification link.

**Comment by roosavihlman** [comment]
Frontend PR: https://github.com/APUOPE-RE/frontend/pull/18
Backend PR: https://github.com/APUOPE-RE/backend/pull/15
